---
slug: django
filename: django
title: Tango with Django
subtitle: Create desktop and web applications with Django.
description: This book is about developing applications with Django.
author: Gerald S. Brown
copyright: 2014
uuid: b96c3cc7-6160-4045-97f4-41e0c4feaa1f
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
