---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
        * Incredibly awesome content
    media:
      - ebooks
    price: 0

  -

authors:
  -
    name: "Gerald S. Brown"
    image: /images/testimonial_1.png
    contact_email: "info@softcover.io"
    bio:
      |
        Author bio [link](https://www.softcover.io)

faq:
  -
    question: "What is Django?"
    answer: "A easy to use framework written with Python for creating web sites an pc applications."

marketing_content: 'A **Free** about creating applications with Django.'

contact_email: 'gbrown@gerbreown.com'
hide_custom_domain_footer: false
